---
title: "Allocating the Value of Insurance Using the 'Split-the-Pie' Approach"
author:
- Rajesh Sahasrabuddhe, Oliver Wyman Actuarial Consulting, Inc.
- Jiale Chen, The University of Connecticut
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document: 
    fig_caption: yes
    number_sections: true
abstract: "In [Split the Pie: A Radical New Way to Negotiate](https://insights.som.yale.edu/insights/better-way-to-divide-the-pie) [@nalebuff2022], Professor Barry Nalebuff of the Yale School of Management proposes an approach for allocating the value created by reaching an agreement. 

The risk sharing created by insurance products creates value through capital allocation efficiency. In our research, we will apply the principles of the split-the-pie approach to the allocation of that value. The analysis will consider the (potential) parties in the value creation: current insureds, prospective insureds, and the insurer. 

We do not intend to contrast the split-the-pie approach with current approaches to profit provisions. Consequently, we do not intend to discuss the merits of the split-the-pie allocation approach. The split-the-pie approach represents a value-based alternative to determining the profit provision in insurance rates. Actuaries may use the research to determine rates and premiums." 

---
<!-- Set knitr options -->

<!-- R Markdown: The Definitive Guide -->
<!-- https://bookdown.org/yihui/rmarkdown/ -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\raggedright
<!-- header-includes: \usepackage{setspace}\doublespacing -->
<!-- Section 1: Introduction -->
```{r child = here::here('paper', '01-00 introduction.Rmd')}
```

<!-- Section 2: Split the Pie -->
```{r child = here::here('paper', '02-00 split the pie.Rmd')}
The "Split the pie" method is a negotiation strategy created by Barry Nalebuff, the Milton Steinbach Professor of Management at the Yale School of Management. The "pie" in this method represents additional resources above what the parties already possess. For instance, money, stock, time, or other assets. Two parties must agree to negotiate the total size of the "pie", or total amount of sources that are available and work together to divide it in a fair and satisfying manner that is fair and satisfactory.

The next step, after determining the size of the "pie," is to identify the factor that determines how to divide the "pie." These factors may include the amount of effort each party will contribute to the project, the level of risk they are willing to accept or any other relevant factors that may impact the distribution of resources.

After identifying factors in the previous step, the parties must evaluate these factors and assign them a numeric value based on their relative importance. If a party believes liquidity to be the most crucial factor, it will assign the factory with the highest numerical value.
Once these values have been assigned, the mathematical formula is used to determine how the “pie” will be split. Despite the fact that the formula used in the “split the pie” method varies depending on the negotiation and factors involve, there are few common methods: 1. Proportional rule. This rule involves dividing the resources based on the proportion of each party's total value to the sum of both parties' values; 2. The Nash bargaining solution The Nash bargaining solution takes into account each party's preferences for each factor and calculates a division of resources that is as close as possible to both parties' ideal outcomes.

The ”split the pie” method is frequently used in negotiation where two parties want to obtain as much as they can from the divided limit resources. By working together to identify the factors which are most important to each parties, assigning numeric value to each factors, and using mathematical formula to determine how they split the “pie”, the parties can arrive at a fair and mutually acceptable distribution.
```

<!-- Section 3: Insurance Pricing -->
```{r child = here::here('paper', '03-00 insurance pricing.Rmd')}
```

<!-- Section 4: A New Approach -->
```{r child = here::here('paper', '04-00 a new approach.Rmd')}
```

